---
- name: Build docker images
  docker_image:
    build:
      path: "{{ exporter_root_path }}/{{ item.name }}"
      pull: false
      dockerfile: "dockerfile"
    name: "{{ item.name }}"
    tag: latest
    source: build
  become: yes
  tags: molecule-notest
  with_items: "{{ exporters }}"
