---
- name: Create Exporter files directories
  file:
    path: "{{ exporter_root_path }}/{{ item.name }}/configs"
    mode: 0755
    recurse: true
    state: directory
  with_items:
    - "{{ exporters }}"

- name: Push config
  template:
    src: "{{ item.1.local_path }}"
    dest: "{{ exporter_root_path }}/{{ item.0.name }}/configs/{{ item.1.local_path | basename }}"
    mode: 0755
  with_subelements:
    - "{{ exporters }}"
    - volumes_files
