---
- name: Set config files
  include_tasks: config.yml

- name: Build docker images
  include_tasks: build_images.yml

- name: Running Docker exporter images
  include_tasks: running.yml
  with_items: "{{ exporters }}"
