---
- name: Create the snmp_exporter container.
  docker_container:
    recreate: true
    name: snmp_exporter
    hostname: snmp_exporter
    image: snmp_exporter
    restart_policy: always
    dns_servers: "{{ snmp_exporter_dns }}"
    ports:
      - "{{ snmp_exporter_web_listen_address }}:{{ snmp_exporter_web_listen_address }}"
    volumes:
      - "{{ exporter_root_path }}/Configs/snmp.yml:/etc/snmp_exporter/snmp.yml:ro"
  tags: molecule-notest
  changed_when: false
  become: true

- name: Create the blackbox_exporter container.
  docker_container:
    recreate: true
    name: blackbox_exporter
    hostname: blackbox_exporter
    image: blackbox_exporter
    restart_policy: always
    dns_servers: "{{ blackbox_exporter_dns }}"
    ports:
      - "{{ blackbox_exporter_web_listen_address }}:{{ blackbox_exporter_web_listen_address }}"
    volumes:
      - "{{ exporter_root_path }}/Configs/blackbox.yml:/etc/blackbox_exporter/config.yml:ro"
  tags: molecule-notest
  changed_when: false
  become: true

- name: Create the ping_exporter container.
  docker_container:
    recreate: true
    name: ping_exporter
    hostname: ping_exporter
    image: ping_exporter
    restart_policy: always
    dns_servers: "{{ ping_exporter_dns }}"
    ports:
      - "{{ ping_exporter_web_listen_address }}:{{ ping_exporter_web_listen_address }}"
  tags: molecule-notest
  changed_when: false
  become: true
