---
- name: Converge
  hosts: all
  vars:
    pip_install_packages:
      - docker-py
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'
    - name: Apply dependancies
      include_role:
        name: "{{ item }}"
      with_items:
        - geerlingguy.pip
        - geerlingguy.docker

  roles:
    - role: justereseau.exporter
